#!/usr/bin/env bash

# Writing this because I don't know how to make Python not buffer stdin.

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while read line
do
    python "${HERE}/speak.py" $line
done < "${1:-/dev/stdin}"
